### ISSUE TITLE
modid is null

### ISSUE THREAD

**Issue by torey0** [yungnickyoung/Better-Caves#11]
Forge 28.1.47
BetterCaves-1.14.4-1.0.0

Having this mod enabled causes all mods to not load. Also present with just this mod alone. 

https://pastebin.com/Qwrygiy8

**Comment by yungnickyoung** [comment]
Hey torey0, using Forge 28.1.47 with BetterCaves-1.14.4-1.0.0 on its own, I have not been able to replicate this issue. I have not yet done testing with other mods.

If you could, please specify the exact actions you take in order for this to occur, and please be as detailed as possible when it comes to your environment. Are you using the mod in the MC client, or on a dedicated server?

**Comment by torey0** [comment]
So it turns out this is a game version issue with the Twitch launcher. Even on a 1.14.4 modpack it by default downloads an old 1.12 version of the mod (which I haven't any other mods behave that way), When checking the different versions available on Twitch only the mentioned 1.14.4-1.0.0 is available so I assumed I had that one. I had the wrong version altogether and didn't catch it (user error). 

I don't know the backend of Twitch/Curseforge enough to say if some version is mislabeled, but I do find it weird I haven't come across this in 100 other mods yet. Sorry for the confusion.

**Comment by yungnickyoung** [comment]
Can you elaborate on what you did? It's concerning to me that I may have some mod config messed up that the Twitch app uses. I tried creating a modpack with my mod (and only my mod) in the Twitch app for 1.14 and it seemed to work fine. 

Btw, I'm guessing the reason you only see the 1.14.4 version on the app is because it only shows mod versions that match up with the Minecraft version you're making the pack for. So if you're making a modpack for Forge 28.1.47, for example, it will only show versions of the mod meant to work with that version of Forge.

**Comment by torey0** [comment]
Create new custom profile. Find your mod and hit install, it by default installed the 1.12 version instead of the 1.14 version. 1.14 version is available to manually select when viewing all versions and loads fine.

**Comment by yungnickyoung** [comment]
Well that's weird, I dunno. I did exactly what you said and it installed the 1.14 version for me. I guess I'll chalk it up to some weird behavior in the Twitch app. 

Thanks for taking the time to give me the details!
