### ISSUE TITLE
Cave creation bugged with Twilight Forest dimension.

### ISSUE THREAD

**Issue by TheOnlyMann** [yungnickyoung/Better-Caves#120]
With default config for better caves, the cave generation from the Twilight Forest gets overridden, making the whole dimension caveless.

![](https://cdn.discordapp.com/attachments/648385743718318110/828771052636995615/2021-04-06_08.20.05.png)
(Overworld cave gen with Bettercaves)

![](https://cdn.discordapp.com/attachments/648385743718318110/828771270451527730/2021-04-06_08.21.01.png)
(Twilight Cave generation with Bettercaves)
![](https://cdn.discordapp.com/attachments/648385743718318110/828775232004947978/2021-03-31_19.18.05.png)
(Twilight Cave generation without Bettercaves)

**Comment by The-Bernician-Lamb** [comment]
I'm also experiencing this issue and I'm able to provide a few more details surrounding this.

The mod versions I was using when this happened are as follows:

- Yungs Api: Forge-6
- Better Caves: 1.1.1
- Twilight Forest: 4.0.426
- Forge Version: 36.1.4

Latest Log: https://pastebin.com/7LJATu5J

What appears to happen is caves don't generate in the twilight forest when Better Caves is installed, despite Better Caves being whitelisted to only affect the overworld. This doesn't affect structures that spawn underground, just caves.

I know that caves that are supposed to generate in the twilight forest are the vanilla style caves, that typically spawn near the surface of the overworld. Maybe the way that your mod changes vanilla caves also seems to be affecting the twilight forest because of it's use of vanilla caves? Just a guess. I'm not a developer so feel free to correct me if I'm wrong.

A picture of (non-existent) Twilight Forest cave gen when better caves is installed:
![2021-04-11_00 23 15](https://user-images.githubusercontent.com/64381954/114287464-e389e300-9a5e-11eb-8fdc-da82f34da7c1.png)
(The only underground bits you can see are part of structures)

**Comment by yungnickyoung** [comment]
Considering Better Caves works fine in any other modded dimension, I have to say this is an error on Twilight Forest's side.

**Comment by The-Bernician-Lamb** [comment]
I've created a temporary solution to this via Better Cave's Config files, I'll put them below in case anyone wants to use the files.:
https://gist.github.com/NJL5390/80ab28ef5e44ffe8efbab9a01ec17014

**Comment by yungnickyoung** [comment]
Thanks. If you want the caves to be more like vanilla, you can also disable Type 1 and Type 2 caves, disable  caverns, and enable Vanila caves in the config.

**Comment by The-Bernician-Lamb** [comment]
> Thanks. If you want the caves to be more like vanilla, you can also disable Type 1 and Type 2 caves, disable caverns, and enable Vanila caves in the config.

I know, I've just been playing through Twilight Forest with Type 1 and 2 caves enabled for a while now and I thought that they fitted in quite well :)

Plus they don't interfere with Twilight Forest's structures at all!

**Comment by yungnickyoung** [comment]
Awesome, glad to hear it :)
