### ISSUE TITLE
Strawberries from Neapolitan generate underground when YBC is installed

### ISSUE THREAD

**Issue by pm065** [yungnickyoung/Better-Caves#128]
See Neapolitan issue for details: https://github.com/team-abnormals/neapolitan/issues/86

**Comment by yungnickyoung** [comment]
In the issue you linked, bagel dismisses the issue as being on my end, but I'm not convinced of that, since no other features using default patch generation have this issue. I wish they would have investigated a bit more rather than closing the issue instantly. Regardless, I'll be closing this report as it is a very minor issue, and Better Caves is basically a finished project at this point.
