### ISSUE TITLE
Why is there no 1.17?

### ISSUE THREAD

**Issue by srnyx** [yungnickyoung/Better-Caves#136]

**Comment by yungnickyoung** [comment]
This is a place for issue reports, not questions about version ports. Please keep those to the Discord.

From the discord FAQ: 

"I know a lot of people want 1.17 ports asap, and believe me, I want it too. But porting 5+ large mods takes a lot of time, and I already have a full-time job + several other projects I'm working on (Better Dungeons, YT content, etc). I feel that my limited time would be best spent working on these new projects rather than porting to a version that will only last a few months. If I can I'll try to squeeze in 1.17 ports, but please don't expect them.

For 1.18, I plan on full ports for all of my major mods except Better Caves. I will no longer be developing Better Caves."
