### ISSUE TITLE
Too many caves!

### ISSUE THREAD

**Issue by Gliese-832-c** [yungnickyoung/Better-Caves#19]
My cave rarity is already set to rare everywhere, my biome size is ExtraLarge.
![grafik](https://user-images.githubusercontent.com/55159077/67977251-0718ef00-fc18-11e9-83a1-0b0522b1dc40.png)
Please make it a numerical multiplier, with 0 making every block air, and 2147... making every block stone. (It doesn't have to be exactly like that, just a better way to configure caves).

**Comment by yungnickyoung** [comment]
You're experiencing this because your biome size is ExtraLarge.

Better Caves draws different regions, and generates different types of caves and caverns in each of these regions. When you set the caves to rare, this means regions are more likely to be empty instead of having caves - however, since your biome size is ExtraLarge, when you do find a region designated for spawning caves, there will be quite a lot of caves since it is a large region. 

I suggest making your biome size smaller to see if that gives the behavior you'd like.
