### ISSUE TITLE
Stone border not placed consistently between lava and water in caves

### ISSUE THREAD

**Issue by TelepathicGrunt** [yungnickyoung/Better-Caves#41]
When using the latest 1.14 version of this mod from Github, I noticed that the border that is suppose to separate the lava and water areas that the caves generates is not always placed correctly. 

To reproduce the issue, use the seed: 6099532026304340457 and go to -224, 1, 236. 
Here is a picture of the issue with coordinates and seed shown.
[https://imgur.com/a/8srAfLn](https://imgur.com/a/8srAfLn)

For the most part, this issue isn't very noticeable for players but I still hope this helps!

**Comment by yungnickyoung** [comment]
Hey, thanks for the issue report. This is a known issue for both versions of the mod, although I'm not sure why it happens. 
Theres a big update in the works for the 1.12 version and it will fix this issue by introducing a buffer region between water and lava regions. At this time, it is not planned for 1.14 to receive this update (since the 1.14 version isnt as popular and the update would take a long time to port).

**Comment by yungnickyoung** [comment]
Completely fixed for 1.12.2-2.0 with the introduction of stone buffers between water/lava regions.
This change will be ported to future versions so I'll close the issue.
