### ISSUE TITLE
[1.16.1] Underground generated structures being destroyed by cave gen

### ISSUE THREAD

**Issue by pa1nki113r** [yungnickyoung/Better-Caves#66]
I noticed with some underground structure generation mods such as Dungeon Crawl the structures are being "ripped apart" due to the cave generation overwriting the structure's blocks. Is there any possible way to add an option to prevent the mod from overwriting generated underground structures?

**Comment by yungnickyoung** [comment]
Caves are generated before structures, so this is the structures' intentional behavior (probably to try to make the structures open up to caves, which works for vanilla but not so much for modded cave gen). Check to see if the structure mods you're using have config options for disabling this. If they don't, you'll need to request such a feature from the mod dev.

**Comment by pa1nki113r** [comment]
I figured that was the case, thank you for the quick reply!
