### ISSUE TITLE
Fix MC-124988

### ISSUE THREAD

**Issue by muzikbike** [yungnickyoung/Better-Caves#74]
This mod definitely does way better than vanilla when it comes to water bordering caves, but it is still easy to encounter cases of water being in invalid states.
![2020-09-28_20 41 52](https://user-images.githubusercontent.com/52297970/94479709-1b20f400-01cd-11eb-872b-082ac1e21e6f.png)
![2020-09-28_20 41 57](https://user-images.githubusercontent.com/52297970/94479715-1ceab780-01cd-11eb-891f-dc716f96ef26.png)
![2020-09-28_20 44 27](https://user-images.githubusercontent.com/52297970/94479717-1eb47b00-01cd-11eb-9202-602ebf92ac24.png)
![2020-09-28_20 46 45](https://user-images.githubusercontent.com/52297970/94479721-1fe5a800-01cd-11eb-8dd4-255204984044.png)
![2020-09-28_20 46 53](https://user-images.githubusercontent.com/52297970/94479725-2116d500-01cd-11eb-9dfe-1147d8aac505.png)
![2020-09-28_20 48 47](https://user-images.githubusercontent.com/52297970/94479733-23792f00-01cd-11eb-942f-02940076deb5.png)

**Comment by jonot-cyber** [comment]
They way to solve this is to update this water so that it flows, but the problem is that it would take a really long time to update each water block. An interesting approach to solve this might be to update water when you load the chunk its in, but im not sure about the performance impact of that

Or I might be completely wrong, I don't know.

**Comment by yungnickyoung** [comment]
This is fundamentally something I cannot change. Carvers only have access to the chunk currently being operated. As such, there is no straightforward way to prevent strange water interactions along chunk boundaries.

For the newest versions in Fabric and Forge 1.16, I attempt to schedule fluid ticks so that such water blocks will at least update and flow properly. 1.12 has not yet received this fix, and may not ever receive it, as it is ultimately a minor issue.
