### ISSUE TITLE
1.12.2 Underground ocean mod config

### ISSUE THREAD

**Issue by disastercube** [yungnickyoung/Better-Caves#77]
I tend to make my caverns tall and large to make exploring much more fun, but by doing so, caves under oceans look deformed.
A feature to config caves under oceans would be pretty neat.
Or maybe there already is and I'm just a fool   ツ.

_**Example of a normal underground cavern:**_
![2020-10-10_17 24 51](https://user-images.githubusercontent.com/62697421/95662407-05012500-0b37-11eb-8223-87f0515b2368.png)

_**Example of a cavern under oceans:**_
![2020-10-10_20 15 56](https://user-images.githubusercontent.com/62697421/95662391-e733c000-0b36-11eb-9434-dda6888100d7.png)

**Comment by yungnickyoung** [comment]
The abrupt walls around the edge are due to the algorithm used to close off flooded caverns from non-flooded caverns. Unfortunately it looks a little jank when the caverns are large.

The large stone strip along the ground is spawned to separate lava regions from water regions. Of course, this shouldn't spawn in flooded caverns so I should probably remove it.

**Comment by yungnickyoung** [comment]
Closing since I no longer support 1.12 actively.
